name: adaptive_theme
description: Allows to change between light and dark theme dynamically and add system adaptive theme support.
version: 2.3.1
homepage: https://github.com/birjuvachhani/adaptive_theme

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: '>=2.0.1 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4