name: adaptive_theme
description: Allows to change between light and dark theme dynamically and add system adaptive theme support.
version: 3.7.1
homepage: https://github.com/birjuvachhani/adaptive_theme

screenshots:
  - description: Adaptive Theme Thumbnail
    path: screenshots/theme.png

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: '>=2.0.1 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

topics:
  - theme
  - theming
  - dynamic-theme
  - adaptive-theme
  - theme-switcher

scripts: scripts.yaml