name: adaptive_theme
description: Allows to change between light and dark theme dynamically
version: 0.1.0
homepage: https://github.com/birjuvachhani/adaptive_theme

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0

flutter: