name: adaptive_theme_repo
description: Mono repo with pub workspace for adaptive_theme package.

homepage: https://github.com/birjuvachhani/adaptive_theme

environment:
  sdk: ">=3.11.0 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter

workspace:
  - packages/*

scripts: scripts.yaml