name: Build

on:
  push:
    paths:
      - '**.dart'
      - '**.yaml'
      - '**.yml'
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter --version
      - name: Install dependencies
        run: flutter packages get
      - name: Check Publish Warnings
        run: flutter pub publish --dry-run
