name: Publish Package

on:
  push:
    tags:
    # must align with the tag-pattern configured on pub.dev, often just replace
    #  with [0-9]+.[0-9]+.[0-9]+*
#     - 'v[0-9]+.[0-9]+.[0-9]+*' # tag-pattern on pub.dev: 'v'
    # If you prefer tags like '1.2.3', without the 'v' prefix, then use:
    - '[0-9]+.[0-9]+.[0-9]+*' # tag-pattern on pub.dev: ''
    # If you repository contains multiple packages consider a pattern like:
    # - 'my_package_name-v[0-9]+.[0-9]+.[0-9]+*'
  workflow_dispatch:

jobs:
  publish:
    permissions:
      id-token: write # This is required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter --version
      - name: Install dependencies
        run: flutter packages get
      - name: Format code
        run: dart format --set-exit-if-changed .
      - name: Tests
        run: flutter test .
      - name: Dry Run
        run: flutter pub publish --dry-run
      - name: Publish
        run: dart pub publish --force