name: Tests

on:
  push:
    paths:
      - '**.dart'
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  tests_and_coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Tap Google's Dart formula repository
        run: brew tap dart-lang/dart
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter --version
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: flutter pub get
      - name: Run tests
        run: flutter test --coverage .
      - uses: codecov/codecov-action@v1
        with:
          file: coverage/lcov.info
